
cd glob

i686-linux-android26-clang -I. -c glob.c 
llvm-ar -r ../lib/libglob.a glob.o

cd src/lighttpd-1.4.58/src

i686-linux-android26-clang \
    -g \
    -O2 \
    -Wall \
    -W \
    -Wshadow \
    -pedantic \
    -o \
    lighttpd \
    lighttpd-server.o \
    lighttpd-response.o \
    lighttpd-connections.o \
    lighttpd-h2.o \
    lighttpd-reqpool.o \
    lighttpd-sock_addr_cache.o \
    lighttpd-network.o \
    lighttpd-network_write.o \
    ls-hpack/lighttpd-lshpack.o \
    lighttpd-algo_xxhash.o \
    lighttpd-data_config.o \
    lighttpd-vector.o \
    lighttpd-configfile.o \
    lighttpd-configparser.o \
    lighttpd-base64.o \
    lighttpd-buffer.o \
    lighttpd-burl.o \
    lighttpd-log.o \
    lighttpd-http_header.o \
    lighttpd-http_kv.o \
    lighttpd-keyvalue.o \
    lighttpd-chunk.o \
    lighttpd-http_chunk.o \
    lighttpd-stream.o \
    lighttpd-fdevent.o \
    lighttpd-gw_backend.o \
    lighttpd-stat_cache.o \
    lighttpd-plugin.o \
    lighttpd-http_etag.o \
    lighttpd-array.o \
    lighttpd-data_string.o \
    lighttpd-data_array.o \
    lighttpd-data_integer.o \
    lighttpd-algo_md5.o \
    lighttpd-algo_sha1.o \
    lighttpd-algo_splaytree.o \
    lighttpd-fdevent_select.o \
    lighttpd-fdevent_libev.o \
    lighttpd-fdevent_poll.o \
    lighttpd-fdevent_linux_sysepoll.o \
    lighttpd-fdevent_solaris_devpoll.o \
    lighttpd-fdevent_solaris_port.o \
    lighttpd-fdevent_freebsd_kqueue.o \
    lighttpd-connections-glue.o \
    lighttpd-configfile-glue.o \
    lighttpd-http-header-glue.o \
    lighttpd-http_auth.o \
    lighttpd-http_date.o \
    lighttpd-http_vhostdb.o \
    lighttpd-rand.o \
    lighttpd-request.o \
    lighttpd-sock_addr.o \
    lighttpd-safe_memclear.o \
    lighttpd-mod_access.o \
    lighttpd-mod_accesslog.o \
    lighttpd-mod_alias.o \
    lighttpd-mod_auth.o \
    lighttpd-mod_authn_file.o \
    lighttpd-mod_cgi.o \
    lighttpd-mod_deflate.o \
    lighttpd-mod_dirlisting.o \
    lighttpd-mod_evasive.o \
    lighttpd-mod_expire.o \
    lighttpd-mod_extforward.o \
    lighttpd-mod_fastcgi.o \
    lighttpd-mod_flv_streaming.o \
    lighttpd-mod_indexfile.o \
    lighttpd-mod_proxy.o \
    lighttpd-mod_redirect.o \
    lighttpd-mod_rewrite.o \
    lighttpd-mod_rrdtool.o \
    lighttpd-mod_scgi.o \
    lighttpd-mod_secdownload.o \
    lighttpd-mod_setenv.o \
    lighttpd-mod_simple_vhost.o \
    lighttpd-mod_ssi_exprparser.o \
    lighttpd-mod_ssi_expr.o \
    lighttpd-mod_ssi.o \
    lighttpd-mod_staticfile.o \
    lighttpd-mod_status.o \
    lighttpd-mod_uploadprogress.o \
    lighttpd-mod_userdir.o \
    lighttpd-mod_usertrack.o \
    lighttpd-mod_vhostdb.o \
    -L../../../lib \
    ../../../lib/libpcre.a \
    ../../../lib/libglob.a \
    -lz